#spring.application.name=homio
server.port=9090
app.jwt.secret=mySuperSecretKey1234567890!@#$
app.jwt.expirationMs=86400000 # Token expires in 1 day (milliseconds)
debug=INFO

# JWT config
#jwt.secret=yourSuperSecretKey12345
#jwt.expiration-ms=86400000 # 1 day

# Gmail SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=razaalinaqvi1234@gmail.com
spring.mail.password=ozhx msrk hgnr fzia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Gmail SMTP config (for example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=razaalinaqvi1234@gmail.com
spring.mail.password=txcqelmbbfjprldu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#spring.datasource.url=jdbc:postgresql://homeroha-db.c5eco2okm8nl.ap-south-1.rds.amazonaws.com:5432/homeroha
#spring.datasource.username=homeroha_user
#spring.datasource.password=D7ryHheppq
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## Optional logging
#logging.level.org.hibernate.SQL=debug